Traceback (most recent call last):
  File "snippet.py", line 4, in <module>
    f = File(open('path_to_file','r'))
IOError: [Errno 2] No such file or directory: 'path_to_file'
