Traceback (most recent call last):
  File "snippet.py", line 102, in <module>
    main()
  File "snippet.py", line 97, in main
    processImage('foo.gif')
  File "snippet.py", line 58, in processImage
    mode = analyseImage(path)['mode']
  File "snippet.py", line 34, in analyseImage
    im = Image.open(path)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'foo.gif'
