Traceback (most recent call last):
  File "snippet.py", line 32, in <module>
    main()
  File "snippet.py", line 5, in main
    main = Image.open("12voltm.jpg")
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '12voltm.jpg'
